### ISSUE TITLE
Atom menus looks bad

### ISSUE THREAD

**Issue by miguelcarax** [nana-4/Flat-Plat#65]
Atom menu's looks bad (on ArchLlinux Gnome 3.20)

![image](https://cloud.githubusercontent.com/assets/9194709/17927959/8b2b42bc-69f8-11e6-9c6d-3140440525c8.png)

**Comment by nana-4** [comment]
I can't reproduce this. Does this happen only in Flat-Plat?

**Comment by miguelcarax** [comment]
And original Adapta too.

**Comment by nana-4** [comment]
> original Adapta

WTF o_O

BTW, does it happen with other themes like Adwaita, Arc, etc.?

**Comment by miguelcarax** [comment]
With adwaite looks like this...
![image](https://cloud.githubusercontent.com/assets/9194709/18005077/0c4eb54a-6b98-11e6-8283-e70516725014.png)

![image](https://cloud.githubusercontent.com/assets/9194709/18005068/00fd5f98-6b98-11e6-822b-d8cb761c94e0.png)

**Comment by nana-4** [comment]
Thank you for your screenshot.
Hmm, that's strange.
There is no problem on my environment. :/
![image](https://cloud.githubusercontent.com/assets/9556384/18005595/d49bf8b8-6bd5-11e6-9b28-2f05da206812.png)

**Comment by miguelcarax** [comment]
I uninstalled atom from official repositories and installed from AUR package and now menu looks like yours but the menu bar looks bad

 
![image](https://cloud.githubusercontent.com/assets/9194709/18006167/99cdad08-6b9e-11e6-97eb-b3ea95af12f2.png)

**Comment by nana-4** [comment]
That's good. The menubar was just fixed now. See #63
So I'll close this. :)

**Comment by daltones** [comment]
I'm still having the same problem of black selection on atom menus. (Arch Linux, Gnome 3.22, Atom 1.12.x, updated [flatplat-theme-git](https://aur.archlinux.org/packages/flatplat-theme-git/))

![captura de tela de 2016-11-29 02-36-25](https://cloud.githubusercontent.com/assets/5603632/20696801/e3e99414-b5dc-11e6-8349-da6ec6066a98.png)


But I noticed that the problem only occurs with the [official package](https://www.archlinux.org/packages/community/x86_64/atom/). The [AUR package](https://aur.archlinux.org/packages/atom-editor-bin/) works fine.

I think there's a problem with the electron version required by the official package. The AUR package depends on an older electron. I guess that's the big difference between the two.

Also I noticed that this issue doesn't occur on Adwaita and Arc in any of the two packages.

**Comment by nana-4** [comment]
@daltones 
Hmm, that's very strange.
Because I do not give any special styling to Atom.
I tried installing Atom on the latest Ubuntu and Fedora from the [official website](https://atom.io/), but there was no visual problem.
Anyway, I'll try to solve the issue if I have time.

Thanks for your information.

**Comment by daltones** [comment]
@nana-4 yeah, you'll won't be able to see the issue from the _official Atom_ distribution. It's quite the same of the [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/) from AUR (that works good on Arch Linux). It actually downloads the official `.deb` file and do the installation from it. This official Atom v1.12.6 includes **Electron v1.3.9**.

But the [atom](https://www.archlinux.org/packages/community/x86_64/atom/) package from Arch Linux official repository (not Atom official) has a patch to exclude the shipped Electron and use the one standalone installed. Then that same Atom v1.12.6 is forced to run with **Electron v1.4.10** (most updated stable).

Looking at the [electron](https://www.archlinux.org/packages/community/x86_64/electron/) package from Arch Linux official repository, I discovered that they also patch it to use GTK3 (electron official still uses GTK2). I think that here is the main problem.

So it's kind of hard for you to reproduce it without Arch Linux. 😅 

Anyway, thanks for now! And also thanks for this great theme! 😃

**Comment by nana-4** [comment]
@daltones Oh, I see.
Now I cannot make sure it because I have no Arch environment. But I may have understood the cause.
Thanks for the detailed information. It helped! 😃

**Comment by ahmadfiroz** [comment]
Workaround for arch linux: Simply install [atom editor bin](https://aur.archlinux.org/packages/atom-editor-bin/) via yaourt or any AUR pm . Its prebuilt binary from official repo and uses gtk 2. plus remove the official atom and electron (atom will conflict) electron wont be needed.

**Comment by nana-4** [comment]
Added a fix for now. Please let me know if there are any problems remaining (except for `accelerator` on the right of the menuitem).

**Comment by daltones** [comment]
@nana-4 That's pretty good for now! As you pointed in the code, waiting for upstream fix…

Thank you! 😃
